---
spring:
  profiles: cold-noun

words: icicle,refrigerator,blizzard,snowball

server:
  port: ${PORT:${SERVER_PORT:0}}

---

spring:
  profiles: normal-noun

words: boat,book,vote,seat,backpack,partition,groundhog

server:
  port: ${PORT:${SERVER_PORT:0}}
